name: Erik's website
markdown: kramdown
hightlighter: pygments

description: philosophy of language centric notes
url: http://erikhoversten.org

scripts: [open,scroll]
styles: [ewob-main]
assets: "https://rawgit.com/ehovers10/ehovers10.github.io/master/"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "elay1"

#gems: ['jekyll/tagging']
exclude: [deprecated,non-jekyll-indices,CNAME,README.md]

sitemap:
  exclude:
    - "/blog/feed.xml"
  include_posts: "/blog/index.html"

pandoc:
  options:
    smart: true
    mathjax: true

scholar:
  source: ./_bibliography
  bibliography: language

tag_page_layout: tag
tag_page_dir: ./blog/tag
