title: Erik Hoversten
author: Erik Hoversten
description: a webspace
url: http://erikhoversten.org
email: "ehovers10@gmail.com"
github: ehovers10
copy: true

markdown: kramdown
scripts: [open,scroll]
styles: [ewob-main,resume]
assets: "/assets/"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "lamps"
  -
    scope:
      path: "compost"
    values:
      layout: "compostlay"

#gems: ['jekyll/tagging']
exclude: [deprecated,non-jekyll-indices,CNAME,README.md]
