name: Erik's website
markdown: redcarpet
hightlighter: pygments

description: philosophy of language centric notes
url: http://erikhoversten.org

scholar:
  source: ./_bibliography
  bibliography: language
  
tag_page_layout: tag
tag_page_dir: ./blog/tag

reveal:
    controls: true
    progress: true
    slideNumber: false
    history: false
    keyboard: true
    overview: true
    center: true
    touch: true
    loop: false
    rtl: false
    fragments: true
    embedded: false
    autoSlide: 0
    autoSlideStoppable: true
    mouseWheel: false
    hideAddressBar: true
    previewLinks: false
    transition: 'default' ## default/cube/page/concave/zoom/linear/fade/none
    transitionSpeed: 'default' ## default/fast/slow
    backgroundTransition: 'default' ## default/none/slide/concave/convex/zoom
    viewDistance: 3
    parallaxBackgroundImage: '' ## e.g. "'https://s3.amazonaws.com/hakim-static/reveal-js/reveal-parallax-1.jpg'"
    parallaxBackgroundSize: '' ## CSS syntax, e.g. "2100px 900px"

