name: Erik's website
markdown: kramdown
hightlighter: pygments

description: philosophy of language centric notes
url: http://erikhoversten.org

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "elay1"
      
gems: ['pandoc-ruby']

sitemap:
  exclude: 
    - "/blog/feed.xml"
  include_posts: "/blog/index.html"

pandoc: 
  options: 
    smart: true
    mathjax: true

scholar:
  source: ./_bibliography
  bibliography: language
  
tag_page_layout: tag
tag_page_dir: ./blog/tag
